name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  ARM_CLIENT_ID:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

  ARM_CLIENT_SECRET:  # id of input
    description: 'Who to greet'
    required: true
    default: 'wO-JpnjUr5xFCjNn3XzSv~D2KVvwMpk.v3'

  ARM_SUBSCRIPTION_ID:  # id of input
    description: 'Who to greet'
    required: true
    default: '47bb1c58-ee41-477f-9ba8-ef0d878cfb29'

  ARM_TENANT_ID:  # id of input
    description: 'Who to greet'
    required: true
    default: '77e30fb9-ddb4-4a65-a17c-96d895261ec5'

  ARM_ACCESS_KEY:  # id of input
    description: 'Who to greet'
    required: true
    default: 'e47+5cSqcXeYEtHMMfd05/fdBagS4f0Bh8KnXUhKzIHn0ZbJie5IIkPSWtzYp+/3uQuSCf4Y2sMdBMUI2xYZaw=='


outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ARM_CLIENT_ID }}
    - ${{ inputs.ARM_CLIENT_SECRET }}
    - ${{ inputs.ARM_SUBSCRIPTION_ID }}
    - ${{ inputs.ARM_TENANT_ID }}
    - ${{ inputs.ARM_ACCESS_KEY }}
