FROM mod

ARG tf_version=1.0.0
ARG ARM_CLIENT_ID
ARG ARM_CLIENT_SECRET
ARG ARM_SUBSCRIPTION_ID
ARG ARM_TENANT_ID
ARG ARM_ACCESS_KEY

ENV ARM_CLIENT_ID=$ARM_CLIENT_ID
ENV ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
ENV ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
ENV ARM_TENANT_ID=$ARM_TENANT_ID
ENV ARM_ACCESS_KEY=$ARM_ACCESS_KEY

WORKDIR $GOPATH/src/app/test/

#COPY *.tf $GOPATH/src/app
#COPY ./test/*.go $GOPATH/src/app/test/
#COPY ./test/*.sh $GOPATH/src/app/test/

CMD bash

