on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: false
          tags: hustakin/hello-world-docker-action:latest
          build-args: |
            ARM_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID_W }}
            ARM_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET_W }}
            ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID_W }}
            ARM_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID_W }}
            ARM_ACCESS_KEY=${{ secrets.AZURE_ARM_ACCESS_KEY_W }}
      
      - name: run
        uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}:/go/src/app
          image: hustakin/hello-world-docker-action:latest
          run: ./testgo.sh
      
