on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          tags: hustakin/hello-world-docker-action:latest
          build-args: |
            ARM_CLIENT_ID=0cf27742-7d47-41b9-ab5c-c6b30f9cb3a9
            ARM_CLIENT_SECRET=ygv2cu5tS96jlH7UyLixLNPt0SgY~3Azdg
            ARM_SUBSCRIPTION_ID=47bb1c58-ee41-477f-9ba8-ef0d878cfb29
            ARM_TENANT_ID=77e30fb9-ddb4-4a65-a17c-96d895261ec5
            ARM_ACCESS_KEY=e47+5cSqcXeYEtHMMfd05/fdBagS4f0Bh8KnXUhKzIHn0ZbJie5IIkPSWtzYp+/3uQuSCf4Y2sMdBMUI2xYZaw==
