on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to build and push docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        run: |
          docker run --rm --env-file my-env.txt -v ${GITHUB_WORKSPACE}:/go/src/app yosrijendoubi/sec /bin/bash ./testgo.sh
      
